imsys/cake/urls.py
from django.urls import path
from . import views

app_name = 'cake'

urlpatterns = [
    #管理员登录页面
    path("", views.index,name='cake'),
    path('login/',views.login,name='login'), #登录界面
    path('register/',views.register,name='register'), #注册界面
    path('logout/',views.logout,name='logout'), #创建路由 
    path('image/code/',views.image_code,name='check_code'), #获取验证码 

    #登录账号管理
    path('login/manage/',views.manage,name='manage'), #创建路由 
    path('login/manage/add/',views.add_user_info,name='manage_add'), #用户添加
    path('login/manage/delete/<int:id>/',views.delete_user_info,name ='delete'), #用户添加
    path('login/manage/<int:id>/edit/',views.edit_user_info,name = 'edit'), #用户编辑修改
    path('login/manage/<int:id>/reset/',views.reset_user_info,name = 'reset'), #用户编辑修改
    
    #员工管理页面
    path('login/staff/',views.staff_manege,name ='staff'), #用户编辑修改
    path('login/staff/add/',views.staff_add,name ='staff_add'), #用户编辑修改
    path('login/staff/staff_edit/<int:id>/',views.staff_edit,name ='staff_edit'), #订单添加页面
    path('login/staff/delete/<int:id>/',views.staff_delete,name ='staff_delete'), #用户添加

    #订单管理页面
    path('login/order/',views.order_manage,name ='order'), #订单管理页面
    path('login/order/add/',views.order_add,name ='order_add'), #订单添加页面
    path('login/order/<int:id>/edit/',views.order_edit,name ='order_edit'), #订单添加页面
    path('login/order/delete/<int:id>/',views.order_delete,name ='order_delete'), #删除订单

]

imsys/imsys/urls.py
from django.contrib import admin
from django.urls import path,include
# from cake import views #直接将路由设置到根页面 不在需要include包括各个app中的url
from cyanine import views as cyanine

urlpatterns = [
    path("admin/", admin.site.urls),

    #展示主界面
    path('',cyanine.main,name='main'),

    #蛋糕店管理系系统demo
    path('cake/',include('cake.urls'))
]

imsys/cake/models.py
from django.db import models
import datetime


#系统用户管理
class UserInfo(models.Model):
    #verbose_name就是对列名的注解 可写可不写 写上为好
    name = models.CharField(verbose_name='用户名',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=64)
    identify = models.ForeignKey(verbose_name='所属员工',to='Staff',to_field='id',null=True,blank=True,on_delete=models.SET_NULL)
    #django默认命名表名方式 app_类名（全小写） 
    #k可以通过Meta元信息进行自定义 例如表明、索引、

#员工表单
class Staff(models.Model):
    name = models.CharField(verbose_name='员工姓名',max_length=32)
    age = models.IntegerField(verbose_name='员工年龄')
    gender_choice = (
        (1,'男'),
        (2,'女'),
    ) #注意是元组套元组
    gender = models.SmallIntegerField(verbose_name='性别',choices = gender_choice)
    phonenumber = models.CharField(verbose_name='员工联系方式', max_length=32)
    create_time = models.DateField(verbose_name='入职时间')

    def __str__(self):
        return self.name

#顾客表单
class Customer(models.Model):
    name = models.CharField(verbose_name='顾客姓名',max_length=32)
    age = models.IntegerField(verbose_name='顾客年龄')
    birthday = models.DateField(verbose_name='顾客生日')
    phonenumber = models.CharField(verbose_name='顾客联系方式', max_length=32)
    gender_choices = (
        (1,'男'),
        (2,'女'),
    ) #注意是元组套元组
    gender = models.SmallIntegerField(verbose_name='顾客性别',choices = gender_choices)
    create_time = models.DateTimeField(verbose_name='注册时间',blank=True,null=True,default=datetime.date(1900,1,1))

    def __str__(self):
        return self.name

#定制订单表单
class Orderform(models.Model):
    starttime = models.DateTimeField(verbose_name='订单产生时间')
    presettime = models.DateTimeField(verbose_name='订单预定完成时间',null=True,blank=True, default=None)
    endtime = models.DateTimeField(verbose_name='订单实际结束时间',null=True,blank=True, default=None)
    customer = models.ForeignKey(verbose_name='顾客信息',to='Customer', to_field='id',null=True,blank=True,on_delete=models.SET_NULL)
    amount = models.FloatField(verbose_name='订单金额')
    commodity = models.CharField(verbose_name='商品名字',max_length=128)
    # orderuuid
    #设置一个status字段代表订单的几种状态：已下单、已完成、未完成、推迟、取消
    status_choices = (
        (1,'已下单'),
        (2,'制作中'),
        (3,'已完成'),
        (4,'推迟'),
        (4,'取消'),
    )
    status = models.SmallIntegerField(verbose_name='订单状态',choices=status_choices,default=1)

#商品清单
class Goods(models.Model):
    name = models.CharField(verbose_name='商品名字',max_length=128)
    serialnumber = models.CharField(verbose_name='商品编号',max_length=128)
    price = models.FloatField(verbose_name='商品价格')
    # count = models.IntegerField(verbose_name='商品库存数量',default=0)
#考虑倒没有库存管理模块 因此舍去数量参数

imsys/templates/add_info.html
{% extends 'nav.html'%}

{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post">
            <h2>添加新的帐号信息</h2>
            {% csrf_token %}
            {% for field in userform %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认添加</button>
        </form>
    </div>    
</div>
{% endblock nav %}

imsys/templates/edit_info.html
{% extends 'nav.html'%}

{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post">
            <h2>修改账号信息</h2>
            {% csrf_token %}
            {% for field in userform %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认添加</button>
        </form>
    </div>    
</div>
{% endblock nav %}

imsys/templates/error.html
{% extends 'nav.html'%}
{% load static %}
{% block nav %}

<h1>啊哦~您的请求并不存在</h1>
<h1>404 Not Found</h1>

{% endblock %}

imsys/templates/goods.html
<head>
    <title>客户界面 - 蛋糕店管理系统</title>
    <meta charset="utf-8">、
    {% load static %}
    <link rel="stylesheet" href="{% static '\bootstrap\css\bootstrap.css' %}">
    <script src="{% static '\jquery-3.7.0.js' %}"> </script>
</head>
<body>

    <button type="button" class="btn btn-primary" id="btn">
        Launch demo modal
      </button>
      
      <!-- Modal -->
      <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
       
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div>

      




    <script src="{% static '/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script>
        $(function () {
            bindBtn();
        })
        function bindBtn() {
            $('#btn').click(function() {
                $('#exampleModal').modal('show');
            })
        }
    </script>

</body>

imsys/templates/info_reset.html
{% extends 'nav.html'%}

{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post">
            <h2>重置密码 </h2>
            <div class="container">
                <figure class="text-end">
                    <blockquote class="blockquote">
                      <p>账号 - {{ user_name }}</p>
                    </blockquote>
                    <figcaption class="blockquote-footer">
                        所属员工 - {{ user_identify }}
                    </figcaption>
                  </figure>
            </div>
            {% csrf_token %}
            {% for field in user_info %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认</button>
        </form>
    </div>    
</div>
{% endblock nav %}

imsys/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <title>cyanine</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        html {
            height: 100%;
        }
        body {
            height: 100%;
        }
        .my-container {
            height: 100%;
            background-image: linear-gradient(to right, #fbc2eb, #a6c1ee);
        }
        .my-login-wrapper {
            background-color: #fff;
            width: 358px;
            height: 588px;
            border-radius: 15px;
            padding: 0 50px;
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
		.my-title{
            font-size: 30px;
            font-weight: bold;
            text-align: center;
            line-height: 100px;
		}
        .my-header {
            font-size: 30px;
            font-weight: bold;
            text-align: center;
            line-height: 100px;
			width: 100%;
        }
        .my-input-item {
            display: block;
			border-radius: 15px;
            width: 100%;
			margin-top: 15px;
            margin-bottom: 20px;
            border: 0;
            padding: 10px;
            border-bottom: 1px solid rgb(128, 125, 125);
            font-size: 15px;
            outline: none;
			padding:10px 0;
			text-indent:10px
        }
        .my-input-item:placeholder {
			border-radius: 15px;
            text-transform: uppercase;
        }
        .my-btn {
            text-align: center;
            padding: 10px;
            width: 30%;
            background-image: linear-gradient(to right, #a6c1ee, #fbc2eb);
            color: #fff;
            border:0;
			border-radius: 15px;
        }
        .my-msg {
            text-align: center;
            line-height: 88px;
        }
        a {
            text-decoration-line: none;
            color: #abc1ee;
        }
        .my-row{
            display:flex;
            justify-content:space-between;
        }
    </style>
</head>
<body> 
    <div class="nav">

    </div>
    <div class="my-container">
        <div>
            <a href="/" style="color:white"><button style="border-radius: 3px;border-color: white;"><h2>back</h2></button></a>
        </div>
        <div class="my-login-wrapper">
			<div class="my-title">蛋糕店管理系统Demo</div>
            <div class="my-header">登录</div> 
				<form method="POST" action='{% url "cake:login" %}'> 
					{% csrf_token %}
                    {{form.name.label}}
                    {{form.name}}
                    <div>
                        {{form.name.errors.0}}
                    </div>
                    {{form.password.label}}
                    {{form.password}}
                    <div>
                        {{form.password.errors.0}}
                    </div>
                    <div class="my-row" >
                        <div>
                    {{form.code}}
                    <span style="color:red">{{form.code.errors.0}}</span>
                        </div>
                        <div>
                            <img src="{% url 'cake:check_code' %}">
                        </div>
                    </div>
                    <button class="my-btn" type="submit">确认登陆</button>					
                </form>
            <div class="my-msg">
                还没有帐号？
                <a href="{% url 'cake:register' %}">注册</a>
            </div> 
        </div>
    </div>
</body>

</html>

imsys/templates/manage.html
{% extends 'nav.html'%}
{% load static %}
{% block nav %}
    <div>
        <div class="container">
            <a href="{% url 'cake:manage_add' %}">
            <button type="button" class="btn btn-primary btn-success" style="margin-top: 10px;margin-bottom: 10px;">
                添加新的帐号
            </button></a>
            <table class="table table-hover table-bordered" style="background-color: beige;">
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">用户账号</th>
                    <th scope="col">账号密码</th>
                    <th scope="col">帐号所属人</th>
                    <th scope="col" colspan="3">操作</th>
                </thead>
                <tbody>
                    {%if page_query_set%}
                    {% for user in page_query_set%}
                    <tr >
                        <th scope="row">{{user.id}}</th>
                        <td>{{user.name}}</td>
                        <td>*********</td>
                        <td>{{user.identify.name}}</td>
                        <td><a href="{% url 'cake:edit' user.id %}"><button type="button " class="btn btn-warning btn-sm">修改帐号/所属人</button></a></td>
                        <td><button uid="{{user.id}}" type="button" class="btn btn-danger btn-sm delete-btn">删除</button> </td>
                        <td><a href='{% url "cake:reset" user.id %}'><button type="button" class="btn btn-info btn-sm">重置密码</button></a></td>
                    </tr>
                    {%endfor%}
                    {% else %}
                    <tr>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td><a href=#>修改</a></td>
                        <td><a href=#>删除</a></td>
                        <td><a href=#>重置密码</a></td>
                    </tr>
                    {% endif %}
                </tbody>
            </table> 

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                {% if page_html_str %}
                {{page_html_str}}
                {% else %}
                <li class="page-item">
                    <a class="page-link disabled">前一页</a>
                  </li>
                  <li class="page-item active"><a class="page-link" href="?page=1">1</a></li>
                  <li class="page-item">
                    <a class="page-link disabled">后一页</a>
                  </li>
                  {% endif %}
                </ul>
            </nav>
        </div>


        <!-- 删除Modal -->
        <div class="modal" tabindex="-1" id="delete-modal" style="border-color: red;">
            <div class="modal-dialog modal-dialog-centered" >
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">删除</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p >真的要删除吗？一旦删除无法复原。</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                    <button type="button" id="confirm-btn" class="btn btn-primary btn-danger">删除</button>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock nav %}

{% block js %}
<script>
    $(function() {
        var nid;
        btnDelete();
        confirmDelete();
    })


     function btnDelete () {
            $('.delete-btn').click(function() {
                $('#delete-modal').modal('show');
                //获取当前元素行的id
                nid = $(this).attr('uid') //自定义的id
                // console.log(nid);
            })
        }

    function confirmDelete(){
        $('#confirm-btn').click(() => {
            //确认删除 将要删除的id发送到后台
            $.ajax({
                url :'delete/'+nid+'/',
                type : 'GET',
                success : function(data) {
                    if (data.status){
                        alert('删除成功');
                        location.reload();
                    }else{
                        console.log(data.errors)
                    }
                }
            })
            
        })
    }
</script>
{% endblock %}

imsys/templates/nav.html
{% load static %}
<head>
    <title>蛋糕店管理系统</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static '\bootstrap\css\bootstrap.css' %}">
    <script src="{% static '\jquery-3.7.0.js' %}"> </script>
    {% block css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark  " data-bs-theme="dark">
        <div class="container ">
        <a class="navbar-brand" href="{% url 'cake:manage' %}">蛋糕店管理系统</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse " id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'cake:manage' %}">系统账号管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cake:staff' %}">员工管理</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cake:order' %}">订单管理</a>
                    </li>                
                </ul>
                <ul class="navbar-nav navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <div class="dropdown ">
                        <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.session.info.name}}
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end " aria-labelledby="dropdownMenuButton2" style="width:fit-content">
                            <li><a class="dropdown-item" href="#">个人信息</a></li>
                            <li><a class="dropdown-item" href="#">我的资料</a></li>
                            <li><a class="dropdown-item" href="#">其他</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">页面设置</a></li>
                        </ul>
                            <a style="margin-left:10px;" href="{% url 'cake:logout' %}"><button type="button" class="btn btn-secondary btn-sm">退出登录</button></a>
                            <a href="/"><button type="button" class="btn btn-secondary btn-sm" style="margin-left: 5px;">返回主页面</button> </a>
                    </div>
                </ul>
            </div>
        </div>
      </nav>
{% block nav %}

{% endblock nav%}
    <script src="{% static '/bootstrap/js/bootstrap.bundle.js' %}"></script>
{% block js %}

{% endblock %}
</body>

imsys/templates/order_add.html
{% extends 'nav.html'%}
{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post" novalidate >
            <h2>添加新的订单信息</h2>
            {% csrf_token %}
            {% for field in order_form %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认添加</button>
        </form>
    </div>    
</div>
{% endblock nav %}

imsys/templates/order_edit.html
{% extends 'nav.html'%}
{% load static %}
{% block css %}

<link rel="stylesheet" href="{% static '\datetimepicker\css\bootstrap-datepicker.css' %}"> </script>
<link rel="stylesheet" href="{% static '\datetimepicker\css\bootstrap-datepicker.min.css' %}"> </script>

{% endblock %}

{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post" novalidate >
            <h2>修改订单信息</h2>
            {% csrf_token %}
            {% for field in order_edit_form %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认修改</button>
        </form>
    </div>    
</div>

{% block js %}
<script src="{% static '\datetimepicker\js\bootstrap-datepicker.js' %}"> </script>
<script src="{% static '\datetimepicker\js\bootstrap-datepicker.min.js' %}"> </script>

{% endblock %}
<script>
// function changeDatetimeInput(id){
//     var time = $(`#${id}`).val().replaceAll('/','-');
//     $(`#${id}`).attr('type','datetime-local');
//     $(`#${id}`).val(time)
// }
// changeDatetimeInput('id_presettime');
// changeDatetimeInput('id_endtime');
</script>
{% endblock nav %}

imsys/templates/register.html
<h1>用户注册</h1>
<p style="color:red">{{msg}}</p>
<form method="post" action='/register/'>
    {% csrf_token %}
    <input type="text" name="user" placeholder="设置用户名">
    <input type="text" name="password" placeholder="设置密码">
    <button type="submit" value="提交">确认提交</button>
</form>

{% if success_msg %}
{{success_msg}}
<a href="/login/">点我转跳登陆页面</a>
{% else %}
{% endif %}

imsys/templates/staff.html
{% extends 'nav.html'%}
{% load static %}
{% block nav %}
    <div>
        <div class="container">
            <a href="{% url 'cake:staff_add' %}">
                <button type="button" class="btn btn-primary btn-success" style="margin-top: 10px;margin-bottom: 10px;">
                    添加新职员
                </button>
            </a>
            <table class="table table-hover table-bordered" style="background-color: beige;">
                <caption class="caption-top">员工名单</caption>
                
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">员工姓名</th>
                    <th scope="col">员工年龄</th>
                    <th scope="col">性别</th>
                    <th scope="col">电话号码</th>
                    <th scope="col">入职时间</th>
                    <th  scope="col" colspan="2">操作</th>

                </thead>
                <tbody>
                    {% if page_queryset %}
                    {% for staff in page_queryset %}
                    <tr>
                        <th>{{staff.id}}</th>
                        <td>{{staff.name}}</td>
                        <td>{{staff.age}}</td>
                        <td>{{staff.get_gender_display}}</td>
                        <td>{{staff.phonenumber}}</td>
                        <td>{{staff.create_time | date:'Y-m-d'}}</td>
                        <td><a href="{% url 'cake:staff_edit' staff.id %}"><button type="button " class="btn btn-warning btn-sm">修改信息</button></a></td>
                        <td><button uid="{{staff.id}}" type="button" class="btn btn-danger btn-sm delete-btn">删除</button> </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <th>编号</th>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td>No Data</td>
                        <td><a href="#">修改</a></td>
                        <td><a href="#">删除</a></td>
                    </tr>
                    {% endif %}
                </tbody>
            </table> 

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                {% if page_html_str %}
                {{page_html_str}}
                {% else %}
                <li class="page-item">
                    <a class="page-link disabled">前一页</a>
                    </li>
                    <li class="page-item active"><a class="page-link" href="?page=1">1</a></li>
                    <li class="page-item">
                    <a class="page-link disabled">后一页</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>





    <!-- 删除Modal -->
    <div class="modal" tabindex="-1" id="delete-modal" style="border-color: red;">
        <div class="modal-dialog modal-dialog-centered" >
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">删除</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p >真的要删除吗？一旦删除无法复原。</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" id="confirm-btn" class="btn btn-primary btn-danger">删除</button>
            </div>
            </div>
        </div>
    </div>
{% endblock nav %}


{% block js %}
<script>
    $(function() {
        var nid;
        btnDelete();
        confirmDelete();
    })


     function btnDelete () {
            $('.delete-btn').click(function() {
                $('#delete-modal').modal('show');
                //获取当前元素行的id
                nid = $(this).attr('uid') //自定义的id
                // console.log(nid);
            })
        }

    function confirmDelete(){
        $('#confirm-btn').click(() => {
            //确认删除 将要删除的id发送到后台
            $.ajax({
                url :'delete/'+nid+'/',
                type : 'GET',
                success : function(data) {
                    if (data.status){
                        alert('删除成功');
                        location.reload();
                    }else{
                        console.log(data.errors)
                    }
                }
            })
            
        })
    }
</script>
{% endblock %}

imsys/templates/staff_add.html
{% extends 'nav.html'%}
{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post">
            <h2>新增员工信息</h2>
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认提交</button>
        </form>
    </div>    
</div>
{% endblock nav %}

imsys/templates/staff_edit.html
{% extends 'nav.html'%}
{% load static %}
{% block nav %}
<div style="width:50%;margin-left: 25%;margin-top: 25px;">
    <div class="container" >
        <form method="post">
            <h2>添加新的员工信息</h2>
            {% csrf_token %}
            {% for field in staff_edit_form %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{ field }}
                <span style="color:red">{{field.errors.0}}</span>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">确认添加</button>
        </form>
    </div>    
</div>


{% block js %}
<script src="{% static '\bootstrap-datetimepicker.min.js' %}"> </script>
<script src="{% static '\bootstrap-datetimepicker.js' %}"> </script>

{% endblock %}
<script>
$('#id_create_time').datetimepicker({
    bootcssVer:5.3,
    format: 'yyyy-mm-dd',
    language: 'zh-CN',
    todayHighlight:true,//当天日期高亮
    minView:'month', //选择最精确的时间视图 最小/默认为为hour
    autoclose:true,//选择完之后就自动关闭
    pickerPosition:'top'
});
</script>
{% endblock nav %}